### ISSUE TITLE
System Errors

### ISSUE THREAD

**Issue by Lilothestitch16** [asilz/TelltaleDialogEditor#1]
Hi. I'm having trouble using the tool. I get a System Error "The code execution cannot proceed because ucrtbased.dll was not found. Reinstalling the program may fix this problem." and I get this error. Any idea how I can fix this?

![image](https://github.com/user-attachments/assets/f0cabb83-228d-495c-8a1c-3628a1655f21)

**Comment by asilz** [comment]
Hi, can you try adding a "./" to the start of the command? So the command would be
`./dlgEditor env_airportExterior.dlog`

**Comment by Lilothestitch16** [comment]
Sure I'll try that

**Comment by Lilothestitch16** [comment]
It worked but how do I open .d3dmesh, .skl, .anm, .chore in the tool?

**Comment by asilz** [comment]
Same method,
`./dlgEditor sk61_javier_bodyUpper.d3dmesh`
That will open the d3dmesh. It does not actually render the mesh, it will just show you the contents of the d3dmesh file.

Also, do you use ghidra? Have you worked on analyzing the engine?

**Comment by Lilothestitch16** [comment]
I used Ghidra but I don't know how to analyze the engine. I wanted to look into the .anm and see if there was a way to convert .anm to .smd format.

**Comment by asilz** [comment]
I  managed to convert .anm + .d3dmesh + .skl to gltf. You can check the code in my TelltaleDevTool in src/gltf2.c. The code is really messy though. I don't know anything about .smd format though, but I can look into it. 

I can send you my ghidra project for TWD DE which I used to analyze animation. It might help you analyze. Do you have discord so that I can send it to you?

**Comment by Lilothestitch16** [comment]
I do have Discord. It's Lilothestitch16

**Comment by asilz** [comment]
I sent you a friend request.
